#!/bin/bash

# Run linting for frontend and backend
# This avoids dealing with linting phase errors in the CI pipeline
if ! make lint-ci; then
    cat >&2 <<'EOF'

pre-commit: linting failed.

  To address formatting issues, use the respective automatic reformatting tools:
  -> For backend use: make backend-reformat
  -> For frontend use: make frontend-reformat
  
  Carefully review the issues reported by mypy, ESLint, and tsc.
EOF
    exit 1
fi
