"""initial migration

Revision ID: 5ec9458224db
Revises:
Create Date: 2026-02-18 21:05:56.272572

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5ec9458224db"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
