"""initial migration

Revision ID: 5ec9458224db
Revises:
Create Date: 2026-08-30 19:50:29.077736

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ec9458224db"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("CREATED", "ACTIVE", "ARCHIVED", "SUSPENDED", name="projectstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=True)
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.Column(
            "role", sa.Enum("OWNER", "ADMIN", "USER", name="userrole"), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "applications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("git_url", sa.String(length=500), nullable=False),
        sa.Column("branch", sa.String(length=100), nullable=False),
        sa.Column("dockerfile_path", sa.String(length=255), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("env_vars", sa.JSON(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("desired_replicas", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "DEPLOYING",
                "RUNNING",
                "UNHEALTHY",
                "STOPPED",
                "FAILED",
                "DELETING",
                name="appstatus",
            ),
            nullable=False,
        ),
        sa.Column("container_id", sa.String(length=64), nullable=True),
        sa.Column("image_tag", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_deployed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_applications_domain"), "applications", ["domain"], unique=True
    )
    op.create_index(op.f("ix_applications_name"), "applications", ["name"], unique=True)
    op.create_index(
        op.f("ix_applications_project_id"), "applications", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_applications_slug"), "applications", ["slug"], unique=True)
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organizations_name"), "organizations", ["name"], unique=True
    )
    op.create_index(
        op.f("ix_organizations_owner_id"), "organizations", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True
    )
    op.create_table(
        "deployments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CLONING",
                "BUILDING",
                "PUSHING",
                "DEPLOYING",
                "HEALTH_CHECKING",
                "SUCCESS",
                "FAILED",
                "CANCELLED",
                name="deploymentstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "started_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("commit_hash", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_deployments_app_started",
        "deployments",
        ["application_id", "started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deployments_application_id"),
        "deployments",
        ["application_id"],
        unique=False,
    )
    op.create_table(
        "organization_members",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OWNER", "ADMIN", "MEMBER", name="organizationrole"),
            nullable=False,
        ),
        sa.Column(
            "joined_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "organization_id"),
    )
    op.create_table(
        "deployment_logs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("deployment_id", sa.UUID(), nullable=False),
        sa.Column(
            "logged_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("line", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["deployments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deployment_logs_id"), "deployment_logs", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deployment_logs_id"), table_name="deployment_logs")
    op.drop_table("deployment_logs")
    op.drop_table("organization_members")
    op.drop_index(op.f("ix_deployments_application_id"), table_name="deployments")
    op.drop_index("ix_deployments_app_started", table_name="deployments")
    op.drop_table("deployments")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_owner_id"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_name"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_applications_slug"), table_name="applications")
    op.drop_index(op.f("ix_applications_project_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_name"), table_name="applications")
    op.drop_index(op.f("ix_applications_domain"), table_name="applications")
    op.drop_table("applications")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
