"""change deployment logs storage approach

Revision ID: ee1f7622cdcc
Revises: 5ec9458224db
Create Date: 2026-09-06 13:19:27.599493

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ee1f7622cdcc"
down_revision: str | Sequence[str] | None = "5ec9458224db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deployment_logs_id"), table_name="deployment_logs")
    op.drop_table("deployment_logs")
    op.add_column(
        "deployments", sa.Column("log_uri", sa.String(length=255), nullable=True)
    )
    op.add_column("deployments", sa.Column("log_size", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deployments", "log_size")
    op.drop_column("deployments", "log_uri")
    op.create_table(
        "deployment_logs",
        sa.Column("id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("deployment_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "logged_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("line", sa.TEXT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["deployments.id"],
            name=op.f("deployment_logs_deployment_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("deployment_logs_pkey")),
    )
    op.create_index(
        op.f("ix_deployment_logs_id"), "deployment_logs", ["id"], unique=False
    )
    # ### end Alembic commands ###
