name: Deplocker Frontend CD

on:
  push:
    branches: [master]

jobs:
  cd:
    name: Build image
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Stop the running container
        run: docker stop deplocker-ui 2>/dev/null || true

      - name: Delete the stopped container
        run: docker rm deplocker-ui 2>/dev/null || true

      - name: Remove the existing image
        run: docker rmi deplocker-ui:latest 2>/dev/null || true

      - name: Build the new image
        run: docker build -t deplocker-ui .

      - name: Run the container
        run: docker run -d --name deplocker-ui -p "8082:80" --restart always deplocker-ui:latest

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Push image
        run: |
          # Create the GHCR tags and push them to the registry.
          docker tag deplocker-ui:latest ghcr.io/${{github.repository_owner}}/deplocker-ui:${{github.sha}}
          docker tag deplocker-api:latest ghcr.io/${{github.repository_owner}}/deplocker-ui:latest
          docker push ghcr.io/${{github.repository_owner}}/deplocker-ui:${{github.sha}}
          docker push ghcr.io/${{github.repository_owner}}/deplocker-ui:latest

          # Remove the GHCR-belonging tags, and keep only the ':latest' one.
          docker rmi ghcr.io/${{github.repository_owner}}/deplocker-ui:${{github.sha}}
          docker rmi ghcr.io/${{github.repository_owner}}/deplocker-ui:latest
